### ISSUE TITLE
Unable to install with skipDashboards= False

### ISSUE THREAD

**Issue by kaur-ivneet** [databricks-demos/dbdemos#112]
When running the installation, the process fails when executing widget queries. This is because it creates a serverless sql warehouse, which is prohibited in the enterprise I m working for. There is no option to switch to pro warehouse as the job is not deployed and only job run is recorded.

**Comment by QuentinAmbard** [comment]
Hey, which demo is it? Can you share a screenshot with the error?

**Comment by kauriv** [comment]
Apologies, the demo is for the costing and forecasting dashboard (uc04-system-tables)

when installation runs, a job run is kicked off which uses dbdemos-serverless sql warehouse. Since our enterprise blocks any connection to the underlying uc buckets from serverless sql, the job run fails. Since the job is not deployed, I can’t edit the job to change compute configuration. 
Is there a way to skip installing dashboard, and do that manually afterwards? 
I can run the full install if I chose to skip dashboard.
I am away for couple days, so can’t post a screenshot. Hope the above information is sufficient

**Comment by QuentinAmbard** [comment]
yes you need skipDashboards=True
This is due to some limitation in the previous dashboard and I don't know how to solve it. We're moving to lakeview soon and hopefully it'll solve the issue once and for all!

**Comment by kauriv** [comment]
In the interim, is it possible to provide the corresponding queries that powers the dashboard, and steps to follow to put it together?

**Comment by QuentinAmbard** [comment]
Hey, here is a the dashboard in lakeview. I haven't tested it, and you'll need to change the catalog with the forecast where you installed the demo, but it should give you the main queries!
[Cost Management and Forecasting (powered by UC System Tables) (Lakeview).lvdash.json](https://github.com/databricks-demos/dbdemos/files/14788667/Cost.Management.and.Forecasting.powered.by.UC.System.Tables.Lakeview.lvdash.json)

**Comment by QuentinAmbard** [comment]
hey, closing this as everything is now on AI/BI & UC!
