### ISSUE TITLE
"use_current_cluster=True" not being carried to all the tasks in the jobs

### ISSUE THREAD

**Issue by mechevarria** [databricks-demos/dbdemos#127]
The option to use the same compute as the notebook `user_current_cluster=True` isn't carried to the task l`oad_dbsql_and_ml_data` in the Lakehouse for IoT demo. A 13.3 cluster tries to get created instead. This causes the job to fail in environments with classic compute that require the enhanced security plugin (no encryption in transit). The Lakehouse C360 workflow has the same issue. If the current cluster is used for every task, then there is no issue

<img width="1904" alt="Screenshot 2024-06-12 at 3 54 04 PM" src="https://github.com/databricks-demos/dbdemos/assets/2657771/d25c9d0b-0d5f-4af9-a873-a73befe9f7be">

**Comment by QuentinAmbard** [comment]
hey @mechevarria , yes it's sadly by design as we need for now a shared compute to load that. We're working on a broader update to better support serverless compute in our content and hopefully it should improve this. For now I'd recommend you run the notebook query using a warehouse for example, it should do the trick. It's a bit of a temporary workaround

**Comment by QuentinAmbard** [comment]
it should be better with the latest release!
