### ISSUE TITLE
uc-04-system-tables - initialization job failure

### ISSUE THREAD

**Issue by chhayavishwakarma** [databricks-demos/dbdemos#45]
Unable to view the dashboard due to initialization job failure 

<img width="1025" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/7696087/cdef6133-647c-4ca4-8e8f-33586bdbd64a">

**Comment by QuentinAmbard** [comment]
thanks,
I suspect this is because some workspaces / sku don't have enough data.
We did a check but it's at the beginning and not including all the SKU after, I moved it in the UDF.
Could you try with this notebook and let me know if it fixes your issue ?

it's a .dbc as a zip for github, so you have to unzip first and then import it (replace the one that was installed with this new with the fix) 

[02-forecast-billing-tables.dbc.zip](https://github.com/databricks-demos/dbdemos/files/12000652/02-forecast-billing-tables.dbc.zip)


It should also fix the dashboard:

**Comment by chhayavishwakarma** [comment]
@QuentinAmbard  thank you for the update, I gave it a try. however, couldn't understand why below dates doesn't match to dates in filter above. 

<img width="1025" alt="image" src="https://github.com/databricks-demos/dbdemos/assets/7696087/bb477373-b310-4d63-8f6f-b2f9aa511382">

another thing I wanted to check is that, does system tables give cost consumption/notebook ? and job ?

**Comment by QuentinAmbard** [comment]
Awesome, I think it's just because you don't have any data yet, and the graph will plot from the current month (July) and the forecast for the next 4 months (but here it looks like you don't have enough data / consumption this month)
You can try the last quarter to see if you have something?

**Comment by chhayavishwakarma** [comment]
thank you @QuentinAmbard  I will give it a try, how about this ? does system tables give cost consumption per notebook ? and job ?

**Comment by QuentinAmbard** [comment]
it's more compute-based, so per cluster * runtime.
However systems tables are going to add more content to include jobs, warehouse and more very soon :)

**Comment by chhayavishwakarma** [comment]
@QuentinAmbard  - Can I consider systems table as overwatch replacement ?

**Comment by QuentinAmbard** [comment]
I think the vision is that over time you'll at least find the same base information in the system tables as in overwatch. 
If what you need is or will be available in system tables then I'd recommend using that instead of overwatch, it'll be much easier for you to setup and maintain!
I'm closing this, feel free to re-open if you have another question!
