### ISSUE TITLE
dbdemos-'uc-01-acl' (01-Row-Column-access-control)

### ISSUE THREAD

**Issue by shah-irfan** [databricks-demos/dbdemos#47]
Getting this exception when trying to use SET ROW FILTER command 
![image](https://github.com/databricks-demos/dbdemos/assets/121429426/adf86ce7-1c65-456b-b005-3ac77e4741a9)

**Comment by QuentinAmbard** [comment]
Hi @shah-irfan , that's because the preview isn't enabled in your account. 
I thought was enabled for all but I believe it's going to take a few extra weeks so I'm a bit too early with the demo as it's still in preview. I'll add a note on the top.
Meanwhile I'd recommend either waiting a bit (~1 month?) or asking your account team if they can add you to the preview? (I don't know if we still onboard new customers because it's about to go in public preview)

**Comment by QuentinAmbard** [comment]
yes me too, it's a really cool one :) I'll close this ticket for now!
